### ISSUE TITLE
Неточности в README

### ISSUE THREAD

**Issue by leobru** [schors/astramacro#1]
Ваш проект найден по ключевым словам "макроязык астра". 

АСТРА - это пакет макросов для языка ассемблера для БЭСМ-6 (насколько мне известно, не сохранился). 

Макроассемблер БЕМШ для БЭСМ-6 реализовывали в ИПМ (Институте прикладной математики) АН СССР по мотивам макроассемблера IBM/360, поэтому их синтаксис совпадает практически полностью. Англоязычные команды были переведены на русский (например, IBM-овская команда базирования по регистру `USING addr(reg)` была переведена как `УПОТР`), но сохранялась возможность использовать оригинальные. 

Макроассемблер IBM/360 - достаточно мощный (фактически позволяет писать программы, выполняемые во время компиляции, и порождающие команды ассемблера) и на нём был написан [пакет для структурного программирования Concept 14](https://en.wikipedia.org/wiki/Assembly_language#Support_for_structured_programming). Выглядит примерно так: https://skycoast.us/pscott/software/mvs/concept14.html

Упомянутая АСТРА - по-видимому, творческое развитие этого пакета. 

С макроассемблером (без АСТРЫ) можно поиграть здесь: http://mailcom.com/besm6/runitnew.cgi
Выберите "Recursive macro"

**Comment by schors** [comment]
Я кстати не знал такой истории. Это была какая-то поделка к военному шкафу харьковского производства, завод уже в 2000-ом не существовал много лет. Транслятор был написан в 80-ых людьми, с которыми к 2000-му была полностью утеряна связь. Без макросов. Явно с чего-то переписывали, потому что объекты с 70-ых с этой дурой ходят

**Comment by leobru** [comment]
Тогда понятно. АСТРА - это видимо, сокращение от АСсемблерный ТРАнслятор, и его могли придумывать независимо в разных местах.
